### ISSUE TITLE
Critical bug 0.4.13: ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by peci1** [scikit-sparse/scikit-sparse#116]
0.4.12 worked fine on Ubuntu 20.04 with system Python 3.8 .

Now I updated to 0.4.13 and I get the following error:

```
$ sudo pip3 install scikit-sparse
Collecting scikit-sparse
  Downloading scikit-sparse-0.4.13.tar.gz (214 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.2/214.2 KB 5.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: scipy>=0.19 in /usr/lib/python3/dist-packages (from scikit-sparse) (1.3.3)
Requirement already satisfied: numpy>=1.13.3 in /usr/lib/python3/dist-packages (from scikit-sparse) (1.17.4)
Building wheels for collected packages: scikit-sparse
  Building wheel for scikit-sparse (pyproject.toml) ... done
  Created wheel for scikit-sparse: filename=scikit_sparse-0.4.13-cp38-cp38-linux_x86_64.whl size=864027 sha256=c5bbef228037d2b47e04f1025070692d4e60c8452b9ee0c72f3855284a9c31e1
  Stored in directory: /root/.cache/pip/wheels/00/e1/84/ba747998155c4e45213588b132dffa319bbd67ac6dedab7b2f
Successfully built scikit-sparse
Installing collected packages: scikit-sparse
Successfully installed scikit-sparse-0.4.13
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.0.4; however, version 24.0 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
$ python3
Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sksparse.cholmod import cholesky_AAt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sksparse/cholmod.pyx", line 1, in init sksparse.cholmod
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject
```

My environment:

```
$ apt-cache policy libsuitesparse-dev 
libsuitesparse-dev:
  Installed: 1:5.7.1+dfsg-2
  Candidate: 1:5.7.1+dfsg-2
  Version table:
 *** 1:5.7.1+dfsg-2 500
        500 http://cz.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
$ apt-cache policy python3-scipy
python3-scipy:
  Installed: 1.3.3-3build1
  Candidate: 1.3.3-3build1
  Version table:
 *** 1.3.3-3build1 500
        500 http://cz.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        100 /var/lib/dpkg/status
$ apt-cache policy python3-numpy
python3-numpy:
  Installed: 1:1.17.4-5ubuntu3.1
  Candidate: 1:1.17.4-5ubuntu3.1
  Version table:
 *** 1:1.17.4-5ubuntu3.1 500
        500 http://cz.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1:1.17.4-5ubuntu3 500
        500 http://cz.archive.ubuntu.com/ubuntu focal/main amd64 Packages

$ pip3 show numpy
Name: numpy
Version: 1.17.4
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: h5py, Keras-Applications, Keras-Preprocessing, opt-einsum, pylas, scikit-sparse, scikit-umfpack, tensorboard, tensorflow, torchvision
$ pip3 show scipy
Name: scipy
Version: 1.3.3
Summary: SciPy: Scientific Library for Python
Home-page: https://www.scipy.org
Author: 
Author-email: 
License: BSD
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: scikit-sparse, scikit-umfpack
```

According to https://stackoverflow.com/a/75150938/1076564 it seems a piece built by Numpy 1.20+ sneaked into the wheel while I'm using Numpy 1.17. No idea where it got from...

**Comment by cgcgcg** [comment]
I was able to reproduce the issue in a Docker container. Bumping up to `numpy==1.23.5` seems to be sufficient. Guess the requirements removed in #105 were there for a reason..

**Comment by peci1** [comment]
Well, I've now tried 0.4.15 on Python 3.8 and the problem is still there...
