### ISSUE TITLE
two tests fail when using numpy 1.12

### ISSUE THREAD

**Issue by grlee77** [scikit-sparse/scikit-sparse#27]
When trying to add numpy 1.12 based conda package (see conda-forge/scikit-sparse-feedstock#5), two test failures are encountered.  The tests passed on the same CI setup when using numpy 1.11.  The failure on the CI service was using Python 2.7, but I verified the same happens for Python 3.5 on my local machine.

For references the failures are:
```
======================================================================
ERROR: sksparse.test_cholmod.test_complex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/recipe_root_1486080708541/_t_env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/feedstock_root/build_artefacts/recipe_root_1486080708541/_t_env/lib/python2.7/site-packages/sksparse/test_cholmod.py", line 99, in test_complex
    assert_allclose(fc(np.arange(4) * 1j)[:, None],
  File "sksparse/cholmod.pyx", line 850, in sksparse.cholmod.Factor.__call__ (sksparse/cholmod.c:10546)
  File "sksparse/cholmod.pyx", line 846, in sksparse.cholmod.Factor.solve_A (sksparse/cholmod.c:10397)
  File "sksparse/cholmod.pyx", line 899, in sksparse.cholmod.Factor._solve (sksparse/cholmod.c:11850)
  File "sksparse/cholmod.pyx", line 924, in sksparse.cholmod.Factor._solve_dense (sksparse/cholmod.c:12350)
  File "sksparse/cholmod.pyx", line 369, in sksparse.cholmod._error_handler (sksparse/cholmod.c:4399)
CholmodInvalidError: ../Cholesky/cholmod_solve.c:1079: dimensions of L and B do not match (code -4)

======================================================================
ERROR: sksparse.test_cholmod.test_cholesky_matrix_market
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/recipe_root_1486080708541/_t_env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/feedstock_root/build_artefacts/recipe_root_1486080708541/_t_env/lib/python2.7/site-packages/sksparse/test_cholmod.py", line 171, in test_cholesky_matrix_market
    assert_allclose(cholesky(XtX, mode=mode)(Xty), answer)
  File "sksparse/cholmod.pyx", line 850, in sksparse.cholmod.Factor.__call__ (sksparse/cholmod.c:10546)
  File "sksparse/cholmod.pyx", line 846, in sksparse.cholmod.Factor.solve_A (sksparse/cholmod.c:10397)
  File "sksparse/cholmod.pyx", line 899, in sksparse.cholmod.Factor._solve (sksparse/cholmod.c:11850)
  File "sksparse/cholmod.pyx", line 924, in sksparse.cholmod.Factor._solve_dense (sksparse/cholmod.c:12350)
  File "sksparse/cholmod.pyx", line 369, in sksparse.cholmod._error_handler (sksparse/cholmod.c:4399)
CholmodInvalidError: ../Cholesky/cholmod_solve.c:1079: dimensions of L and B do not match (code -4)
```

**Comment by anntzer** [comment]
The issue comes from
```
    cdef np.ndarray _cast(self, np.ndarray arr):
        if not issubclass(arr.dtype.type, np.number):
            raise CholmodError("non-numeric dtype %s" % (arr.dtype,))
        if self._complex:
            # All numeric types can be upcast to complex:
            return np.asfortranarray(arr, dtype=_complex_py_dtype)
        else:
            # Refuse to downcast complex types to real:
            if issubclass(arr.dtype.type, np.complexfloating):
                raise CholmodError("inconsistent use of complex array")
            else:
                return np.asfortranarray(arr, dtype=_real_py_dtype)
```

Specifically, 1d arrays are cast to 2d a bit earlier using `d[:, None]`, which creates an array of strides `(itemsize, 0)`.  With numpy<1.12, `asfortranarray` would then create a new array with strides `(itemsize, len*itemsize)`.  But with relaxed stride checking, this is no longer the case, i.e. the original array of strides `(itemsize, 0)` is returned.

This then causes issue further down at
```
    cdef object _init_view_dense(self, cholmod_dense *out, np.ndarray m):
        if m.ndim != 2:
            raise CholmodError("array has %s dimensions (expected 2)" % m.ndim)
        m = self._cast(m)
        out.nrow = m.shape[0]
        out.ncol = m.shape[1] # oops, this is zero.
        out.nzmax = m.size
        out.d = m.strides[1] // m.itemsize
        out.x = m.data
        out.dtype = CHOLMOD_DOUBLE
        out.xtype = self._xtype
        return m
```

**Comment by njsmith** [comment]
surely the issue must be with cholmod getting cranky at `out.d == 0`, no? According to your analysis, `m.shape[1]` is not zero, only `m.strides[1]` is?

**Comment by njsmith** [comment]
ah, I see your PR came to the same conclusion :-)

**Comment by jor-** [comment]
Version 0.4.1 is released. This should fix this bug. (See PR #28.)
